### ISSUE TITLE
KeyError in line 287 of resource_tracker.py using loky backend, /dev/shm/folder not created?

### ISSUE THREAD

**Issue by matthewhang** [joblib/joblib#1076]
Hi all, 

I am using joblib 0.15.1 installed with conda and encountered the following problems while using the loky backend, there are multiple instances of error similar to the following, the only difference is the folder name (i guess) after /dev/shm.

> KeyError: /dev/shm/joblib_memmapping_folder_71367_e761fc411a594e51bfec8e8002eef735_ea8c40a4eda54696a61ed4d8cb034363/71367-139949476506424-dcad585b155949789780aa7cb571abf7.pkl

when the program end, there is another message:

> /joblib/externals/loky/backend/resource_tracker.py:320: UserWarning: resource_tracker: There appear to be 289 leaked file objects to clean up at shutdown
>   (len(rtype_registry), rtype))

and lots of the following (many repeated warnings, the only difference is the folder name):

> joblib/externals/loky/backend/resource_tracker.py:333: UserWarning: resource_tracker: /dev/shm/joblib_memmapping_folder_7         1367_e761fc411a594e51bfec8e8002eef735_aba7d846e2d7478fb3221a7435a5cbe1/71367-139949476506424-f948a4e70d864c3fb73b6b0dcad7d4b5.pkl: FileNotFoundError(2, 'No such file or directory'         )

However, the program seems to keep running and return some results (not sure if the program is correctly run though)

Any ideas on this? Thanks in advance.

**Comment by pierreglaser** [comment]
Hi, thanks a lot for the report.

These warning messages do not affect the correctness of the results - these are internal messages related to inter-process communication optimization procedures that are implemented in `joblib`. We should downgrade the severity of those messages to `INFO` (which means users won't see them anymore).

Nevertheless, these message are still very informative from a `joblib` developer point of view. That would be really helpful if you could provide us with a [standalone reproducer](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) so that we could investigate things further. Thanks! :)

**Comment by matthewhang** [comment]
> Hi, thanks a lot for the report.
> 
> These warning messages do not affect the correctness of the results - these are internal messages related to inter-process communication optimization procedures that are implemented in `joblib`. We should downgrade the severity of those messages to `INFO` (which means users won't see them anymore).
> 
> Nevertheless, these messages are still very informative from a `joblib` developer point of view. That would be really helpful if you could provide us with a [standalone reproducer](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) so that we could investigate things further. Thanks! :)

Thank you so much for ur response. I have tried to made some reproducible example without including my own data but havent succeed...perhaps it is specialized to my own written class. 

But I could provide another clue that perhaps be useful to you. I downgraded joblib to 0.14.1 to test if the messages would disappear. It turned out my program crashed and couldnt continue due to the followings:

> joblib.externals.loky.process_executor._RemoteTraceback:
'''
Traceback (most recent call last):
  File "python3.6/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "python3.6/site-packages/joblib/_memmapping_reducer.py", line 196, in _strided_from_memmap
    offset=offset, order=order)
  File "python3.6/site-packages/joblib/backports.py", line 23, in make_memmap
    shape=shape, order=order)
  File "python3.6/site-packages/numpy/core/memmap.py", line 225, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/joblib_memmapping_folder_82547_4376857065/82547-140390095683880-44fe9e93b2b0403e9052446a59806895.pkl'

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "analyze_microstates_byclass.py", line 65, in <module>
    ec_group_ms.cal_ms_feat(peaks_itpl=True)
  File "xxxxx.py", line 2498, in cal_ms_feat
    df_list = Parallel(n_jobs=len(self._ms_list), backend='loky')(delayed(feat_worker)(ms) for ms in self._ms_list)
  File "/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

and if I am switching the backend to 'multiprocessing' under joblib 0.14.1, I got the following errors:
> AttributeError: Can't pickle local object 'GroupMicrostates.cal_ms_feat.<locals>.feat_worker'

GroupMicrostates is the class I created and cal_ms_feat() is a class function, feat_worker() is the worker function declared inside cal_ms_feat() to be put in Parallel.

**Comment by pierreglaser** [comment]
> But I could provide another clue that perhaps be useful to you. I downgraded joblib to 0.14.1 to test if the messages would disappear.

The messages mentionning `/dev/shm` **and `resource_tracker.py` that you reported come from a new bugfix that exists only in `joblib 0.15` and later. So no messages like these are expected in `joblib 0.14.1`.

However, your traceback is interesting as it seems to indicate that `joblib` is unable to retrieve a `memmap` object that was creating when serializing the function calls about to be executed inside the children processes. This is very unusual (for `joblib<0.15`), and it may be due to some specificies of your system.

In order for me to investigate this further, I would need a reproducer. If this is not possible, you can disable `memmapping` in joblib using

```python
`Parallel(max_nbytes=None, n_jobs=-1, backend='loky')`
```

The `max_nbytes=None` is the necessary option that you should add to the `Parallel` constructor in your setting.

**Comment by matthewhang** [comment]
> The `max_nbytes=None` is the necessary option that you should add to the `Parallel` constructor in your setting.

Unfortunately this did not work. Stil the same error. By setting verbose=50, I can see all the jobs being completed but the error happened when returning the results.

Not sure what happened, still trying to debug.

**Comment by ogrisel** [comment]
@matthewhang could you please try again with joblib 0.16.0? I do not expect it to solve the problem but the error reporting might make more sense to debug this.

The fact that you get `AttributeError: Can't pickle local object 'GroupMicrostates.cal_ms_feat..feat_worker'` with the multiprocessing backend of joblib 0.14.1 makes me think that there is indeed a problem with the pickling of this class but I do not understand why this error messsage does not show up with the loky backend.

**Comment by matthewhang** [comment]
> @matthewhang could you please try again with joblib 0.16.0? I do not expect it to solve the problem but the error reporting might make more sense to debug this.
> 
> The fact that you get `AttributeError: Can't pickle local object 'GroupMicrostates.cal_ms_feat..feat_worker'` with the multiprocessing backend of joblib 0.14.1 makes me think that there is indeed a problem with the pickling of this class but I do not understand why this error messsage does not show up with the loky backend.

Hi, thanks for the suggestion, I have tried to use multiprocessing backend with joblib 0.16, the same error occurred.
However loky backend is still outputting the same errors as i reported, but at least the process could be completed.

**Comment by matthewhang** [comment]
> @matthewhang could you please try again with joblib 0.16.0? I do not expect it to solve the problem but the error reporting might make more sense to debug this.
> 
> The fact that you get `AttributeError: Can't pickle local object 'GroupMicrostates.cal_ms_feat..feat_worker'` with the multiprocessing backend of joblib 0.14.1 makes me think that there is indeed a problem with the pickling of this class but I do not understand why this error messsage does not show up with the loky backend.

@ogrisel I have recognized the problem. My worker fucntion was nested inside the function in which the `Parallel()` was called, i guess this is regarded as the **local** object that couldnt be pickled. Please see below:

```Python
def function():
    def worker():
    Parallel(backend=''multiprocessing')(delayed(worker))()
```

When I define the worker function separately, it worked without any error messages:
```Python
def worker():

def function():
    Parallel(backend=''multiprocessing')(delayed(worker))()
```

However, when I switch it back to **loky** backend, the same errors I reported still exist even after this change.

**Comment by matthewhang** [comment]
@ogrisel @pierreglaser Thanks for the help and response. I now switched back to the loky backend and the errors disappeared (didnt know why the errors still popped up few days ago). 

I guess avoiding the use of nested worker function is the key to solve this. I will close the issue.

**Comment by ogrisel** [comment]
Indeed loky should be able to deal with nested functions while I am don't think it's the case with the multiprocessing backend.

That does not explain why you don't get the original error any more though. Maybe they are random. If you observe them again it would be great for you to isolate a minimal reproduction case so that we can try to fix the root cause of the problem.

**Comment by PanZiwei** [comment]
Hi, I got a similar problem with `joblib==1.1.0`. To be more specific, I am doing random forest modeling building with sklearn with random search to find the best parameters and save the best model.

It's interesting that the script goes smoothly with the small testing dataset, but it crashed with the real large dataset. I am not sure whether it is crashed since the program is still running with the error log message. 

The error is shown below:
```shell
Traceback (most recent call last):
  File "/Ziwei/Anaconda3/envs/test/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py", line 287, in main
    registry[rtype][name] -= 1
KeyError: '/dev/shm/joblib_memmapping_folder_209071_be605cbda8d24cb8b58e4fb0ede88ff8_3ba79016e9c241a89ea0945d721da241/209071-46914447630592-263c9f9c020242a3a28439d132a26543.pkl'
```
Any updates on the issue solving since the original question is raised last year? 

Also, based on your previous response, should I ignore the error and wait for the program to finish since the warning message is not a big issue? Or I should stop the task to find other solutions?

Thank you so much for your help!

> Hi, thanks a lot for the report.
> 
> These warning messages do not affect the correctness of the results - these are internal messages related to inter-process communication optimization procedures that are implemented in `joblib`. We should downgrade the severity of those messages to `INFO` (which means users won't see them anymore).
> 
> Nevertheless, these messages are still very informative from a `joblib` developer point of view. That would be really helpful if you could provide us with a [standalone reproducer](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) so that we could investigate things further. Thanks! :)
