### ISSUE TITLE
joblib resource tracker process remain alive with sklearn 

### ISSUE THREAD

**Issue by dmoshayof** [joblib/joblib#1153]
Hi,
I'm using sklearn parallelism with joblib several times in the code. 
When the task done, in some cases,  python process with this cmd 
"from joblib.externals.loky.backend.resource_tracker import main; main" 
remain alive.
I tried to add try:finally e.g

 _try:
          **Full flow with sklearn sub-processes**
        finally:
            get_reusable_executor().shutdown(kill_workers=True)_

but there is still running process.
I don't want to overload the system with zombies-
 is it the expected behavior? 
is the process waiting for another task for lazy start? 
does it have timeout if so? or maybe it's a real issue.
Thanks, 
Daniel

**Comment by tomMoral** [comment]
Hello,

If you mean that it stays while your python interpreter is alive, this is
the expeccted behavior.
It is not supposed to go away until the main python process dies.
If it stays for more than a minute after the main process dies, it is not
expected.

The `resource_tracker` is a process that keeps track of system resources
such as
files used for memory mapping and `semaphore` on UNIX systems.
In case of an unexpected crash of the main process, this process will clean
up
left-over resources to make sure in the long run you don't run out of them.

This process should be very light weight (it simply listens on a file
descriptor).
If it is really a performance issue, one improvement could be that we shut
it
down if no resource is currently tracked by it. But I expect this feature
to complicate the
code a lot due to synchronisation when dying so it should really be because
it has an
impact on the system perf.

**Comment by dmoshayof** [comment]
Thanks for the very fast respond.
Good to know that my assumption was true and there is no problem. 
Closing the issue, 
Thanks again :)

**Comment by tomMoral** [comment]
Glad it helped!

On a side note, the same mechanism exists on UNIX system for `multiprocessing` for the `spawn` start method. It is triggered by instantiating a synchronization primitive such as a `Lock`:
```python
from multiprocessing import get_context
get_context('spawn').Lock()
```
This will create a process that will stay until your main interperter is closed.
