### ISSUE TITLE
FEFLOW Parallel computing 

### ISSUE THREAD

**Issue by Benyamin1368** [joblib/joblib#1190]
Hello joblib team,
Currently I am using API function of FEFLOW in python, as the process of simulation is so time-consuming, I decided to parallelize my code, to do that I wrote the following code to compare the running time in parallel and non-parallel mode:

```python
from joblib import Parallel, delayed
import time, math
import ifm

doc=ifm.loadDocument('Aquifroid.fem')
Timesteps=[1,1.1]
def my_fun(i):
    doc.setFinalSimulationTime(Timesteps[i])
    doc.startSimulator()

num = len(Timesteps)
start = time.time()
for i in range(num):
    my_fun(i)
end = time.time()
print('{:.4f} s'.format(end-start))

start = time.time()
Parallel(n_jobs=2)(delayed(my_fun)(i) for i in range(num))
end = time.time()
print('{:.4f} s'.format(end-start))
```

after running this code following error popped up:

```
'PicklingError: Could not pickle the task to send it to the workers.'
```

I will be grateful if you advise me to solve this issue.
Thanks in advance,

**Comment by ogrisel** [comment]
If if define parallel function interactively in your main script, it should only use picklable constructs. The full error message is likely more informative as to what is not picklable in your specific case.

If you cannot make this picklable, just define the `my_fun` function in a module that you import instead of defining that function interactively in the main script / jupyter session.
