### ISSUE TITLE
number of cores used exceeds the n_jobs set by user

### ISSUE THREAD

**Issue by WT215** [joblib/joblib#1268]
Hello,

I submitted a job to PBS. But got the following error:
`PBS: job killed: ncpus 19.38 exceeded limit 8`

In the code, I set `n_jobs=4`,  and `a=Parallel(n_jobs=n_jobs,verbose=0, prefer="threads")(delayed(b)...`

And in PBS script I set
```
#PBS -lselect=1:ncpus=8:mem=96gb
#PBS -lwalltime=72:00:00
```

Not sure why it used more than 4 cores as set in the code.

Thanks!

**Comment by tomMoral** [comment]
Hello,

This is likely due to the fact that `b` also perform some kind of parallel computation, for instance if you are using `numpy`.
Could you give us more information about the function `b`?

Also, why do you rely on `threads` and not the default `backend?

**Comment by WT215** [comment]
Hello,

Thanks for replying! The default backend also suffer from that error, so I changed to `threads`. 

Function `b` is a bit complicated:

```
def sum_sub_wt(i,scRNA,cell_number,repeats,param_space,inputbeta):
    kon = param_space[0][i]
    koff = param_space[1][i]
    ksyn = param_space[2][i]
    #gene = scRNA[i*repeats+j,:]
    gene = scRNA[i,:]
    
    #nonan = ~np.isnan(gene)
    #gene = gene[nonan]
    #inputbeta = inputbeta[nonan]

    raw_m1 = np.mean(gene)
    raw_count = np.sum(gene)

    gene = gene/inputbeta
    counts = np.sum(gene)
    gene = gene/counts

    zcount = len(np.where(gene == 0)[0])/cell_number
    ir = max(gene)-min(gene)
    maxgene = max(gene)
    m1 = np.mean(gene) 
    p10 = np.percentile(gene,5)
    p25 = np.percentile(gene,25)
    p50 = np.median(gene)
    p75 = np.percentile(gene,75)
    p95 = np.percentile(gene,95)
    m2 = np.var(gene)
    m3 = scs.skew(gene) # Third moment, skewness
    m4 = scs.kurtosis(gene) # Fourth moment, kurtosis
    cov = scs.variation(gene)

    abcde = [kon,koff,ksyn,np.log10(ir),np.log10(maxgene),p10,p25,p50,p75,p95,m1,np.log10(m2),m3,m4,np.log10(counts),zcount,np.log10(cov),np.log10(raw_m1),np.log10(raw_count)]
    return  abcde 
```

Another `b` is 
```
def rbp_self(cell_number,kon, koff, ksyn):
    simout=np.random.poisson(np.random.beta(...), somenumber)
    return simout
```

**Comment by tomMoral** [comment]
Ok, so you are using `numpy`.
could you try to set `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1` before launching the computations? This should kill the parallelism in `numpy`.

Also, could you report what happens if you perform a matrix multiplication with numpy?
```python
import numpy as np

A = np.random.rand(10,500)
B = np.random.rand(500,50000)
A @ B
```

Similar issues with cpus leak on PBS have been reported with `numpy` befo, for instance here:
https://stackoverflow.com/questions/59948652/is-numpy-matmul-parallelized-and-how-to-stop-it
What I would like to assess is whether this has been fixed in `numpy` and we are breaking it with our code or if it is something directly due to `numpy`.

If we are breaking the code, this is probably due to our oversubscription mitigation mechanism.

**Comment by WT215** [comment]
Adding `OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1` in PBS script solves the problem, many thanks!

I ran that numpy multiplication code directly in bash, but it took a long time so I terminated that.
