### ISSUE TITLE
Parallel.__init__() got an unexpected keyword argument 'return_generator'

### ISSUE THREAD

**Issue by juleskuehn** [joblib/joblib#1446]
I am on Macbook Air M2, with Python 3.10.11, and joblib 1.2.0

I am getting this error:
`TypeError: Parallel.__init__() got an unexpected keyword argument 'return_generator'`

And sure enough, there is no such argument in the joblib code.

Just like in the documentation, I am trying to do this:
`parallel = Parallel(n_jobs=2, return_generator=True)`

**Comment by juleskuehn** [comment]
I see this is resolved by building 1.3.0 from this git repo. Perhaps the docs could be updated to reflect this (or 1.3.0 pushed to PyPi)

**Comment by tomMoral** [comment]
Hello,

Thanks for the report.
Indeed, this is due to the fact that this feature is in `master` and we have not yet released it. (We should release it in one week).
We need to have one doc for the stable version of `joblib` and one for the dev branch.
This issue is tracked in #1438 so I am closing this one.
