### ISSUE TITLE
`joblib.Parallel` silently fails to re-raise exception when `n_jobs > 1 and n_iterations > n_jobs*2`

### ISSUE THREAD

**Issue by arkanoid87** [joblib/joblib#1489]
switch `BAD_CASE` with `GOOD_CASE` in `iterate_me` call

```python
from joblib import Parallel, delayed

def iterate_me(n):
    for i in range(n):
        assert i != n-1
        yield n

def identity(x):
    return x

N_JOBS = 2
GOOD_CASE = N_JOBS * 2
BAD_CASE = GOOD_CASE + 1

try:
    Parallel(n_jobs=N_JOBS)(delayed(identity)(i) for i in iterate_me(BAD_CASE))
    print("BAD - this line should never be reached")
except Exception:
    print("GOOD - this line should always be reached")
```

current result
```
BAD - this line should never be reached
```
expected result
```
GOOD - this line should always be reached
```
version
```
Python 3.11.3
joblib==1.3.1
```

**Comment by GaelVaroquaux** [comment]
> This makes iterate_me called once, Parallel result truncated where iterate_me reached assert, but AssertionError not raised to main scope

Yes, "iterate_me" is called in the main worker. You cannot have in iterator called in the worker thread/processes. This is not related to joblib, it is related to where iterators are evaluated.

**Comment by tomMoral** [comment]
Hello,

Thanks for taking the time to report this. To be complete about this one, the error is not silent but it prints the following error:
```
exception calling callback for <Future at 0x7f82a37b12d0 state=finished returned list>
Traceback (most recent call last):
  File "HOME/.local/miniconda/lib/python3.10/site-packages/joblib/parallel.py", line 820, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "HOME/.local/miniconda/lib/python3.10/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HOME/.local/miniconda/lib/python3.10/site-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "HOME/.local/miniconda/lib/python3.10/site-packages/joblib/parallel.py", line 359, in __call__
    self.parallel.dispatch_next()
  File "HOME/.local/miniconda/lib/python3.10/site-packages/joblib/parallel.py", line 792, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "HOME/.local/miniconda/lib/python3.10/site-packages/joblib/parallel.py", line 831, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "<ipython-input-3-131681540852>", line 16, in <genexpr>
    Parallel(n_jobs=N_JOBS)(delayed(identity)(i) for i in iterate_me(BAD_CASE))
  File "<ipython-input-3-131681540852>", line 5, in iterate_me
    assert i != n-1
AssertionError
```

The core assumption of `joblib` is that the call is provided with an iterator that does not raise errors, which we cannot check.
So this is not really a bug but indeed we could improve this behavior. :sweat_smile:

The difference between the bad and good cases is where the iterator is consumed. In the good case, because the default dispatch is `2*n_jobs`, all the iterator is consumed in the main thread, the error being also raised and catcher in the main thread.
In the second case, the iterator is consumed asynchronously by the `executor_manager_thread` of `loky`. The error is raised there and not in the main thread, thus the "bad behavior".

I think it would be indeed less surprising for the users to see the error re-raised in the main thread.
This should be doable by catching errors in https://github.com/joblib/joblib/blob/master/joblib/parallel.py#L1431 and re-raising them in the main thread.

---

That being said, I would like to point out that your last answer came across as a bit harsh. This can have a significant impact on the maintainers who dedicate their time to maintaining the project. We understand that frustrations may arise, but it's important to remember that we are all part of a community that thrives on respectful and constructive communication.

As maintainers, we are committed to providing assistance and resolving issues in the best way possible. We encourage you to share your feedback and concerns in a manner that fosters collaboration and understanding. Together, we can find solutions that benefit everyone.

Moving forward, let's continue the discussion with empathy and open-mindedness. Your contributions and engagement are valued, and we want to ensure a positive and welcoming environment for all.

**Comment by tomMoral** [comment]
This is an implicit assumption that is not documented I think (which is not so good :sweat_smile: ).
I think as this is not too complicated to fix the behavior and to remove this assumption, we should focus on merging #1491 rather than improving the doc.
