### ISSUE TITLE
[Question] Parallel with `backend=threading` versus `prefer=threads`

### ISSUE THREAD

**Issue by VincentRouvreau** [joblib/joblib#1511]
Hello and thanks for this library !

I was reading the documentation about Parallel `backend=threading`:
 > “threading” is mostly useful when the execution bottleneck is a compiled extension that explicitly releases the GIL (for instance a Cython loop wrapped in a “with nogil” block or an expensive call to a library such as NumPy).

And that is exactly my case.

I was wondering to know if, from your experience, there are some differences in that case if I say `backend=threading` versus `prefer=threads` ?
This is just to be sure that I pick up the best option.

**Comment by ogrisel** [comment]
This is a way to let joblib know which backend should be preferred by default (to switch between `loky` and `threading`) but it still makes it possible to override this choice from the outside using `parallel_config` (possibly via a context manager) without having to edit the code that calls `Parallel()`.

This is useful to change the backend (e.g. to use `dask` instead of the default backend) when the code that calls `Parallel` (e.g. in the scikit-learn code base) is used from another code (e.g. a jupyter notebook or a library) without having to pass the backend name explicitly everywhere.

If scikit-learn had called `Parallel(backend="threading")` instead of `Parallel(prefer="threads)` then it would no longer be possible to change the backend from the outside using `parallel_config(backend="dask")` because the inner explicit backend param always has the priority.
