### ISSUE TITLE
update cached values

### ISSUE THREAD

**Issue by iuiu34** [joblib/joblib#1559]
Hi,

i want to uodate cached values dynamically.

memory.clear() deletes everything. Is it posible to delete a particular function memory?

Another option, is to use 'cache_validation_callback', but that doesn't seem to fit neither.

example
Imagine, get_user_state, access a big DDBB, I only want to access it, updating local data, in some cases

but if  i do
get_user_state(cache=False)
get_user_state(cache=True)
get_user_state(cache=False)
get_user_state(cache=True)

what happens is
2 != 1
4 == 2

i want,
2 == 1
4 == 3

thanks

**Comment by fcharras** [comment]
Hello @iuiu34 , working at this level of granularity is not currently in the scope of `joblib.Memory` features. I think you _can_ work around this usecase by using underlying backend store API which is described in the module [_backend_store.py](https://github.com/joblib/joblib/blob/master/joblib/_store_backends.py). Some of the backend store API is public since it is intended for users that would like to override the default filesystem backend. You can use it to remember the path (similar to a cache key) to the cache for a given cached item, and specifically delete this single item later based on custom user condition.

Please provide a better reproducer (with runnable python code) of your usecase so we could discuss considering a more direct user-facing public API for this kind of usecases in joblib.
