### ISSUE TITLE
Make it possible to have a function's cache depend on the *contents* of a disk file

### ISSUE THREAD

**Issue by aarchiba** [joblib/joblib#218]
Many of my processing functions act on disk files rather than in-memory arrays. Using joblib's cache checks whether the filename has changed, not the file contents. Perhaps some arrangement where the function acted on a File object, passed by name but whose on-disk contents were checked for changes? 

Alternatively I could arrange to pass in the file contents as a giant string, write it to a temporary file inside the function, call a subprocess, read the output files in as strings, and return them, but that's an awful lot of round-trips to disk when you add in the caching.

**Comment by GaelVaroquaux** [comment]
I really want to avoid having any kind of 'magic': behavior that depends
in a subttle way on context or input argument.

What I would however be ready to add is a 'depends' argument that would
be an object not used by the function, but used in the cache hash
computation (this has been suggested quite a few times, actually). You
could then wire things the way you want.

**Comment by aarchiba** [comment]
Yes, magic is trouble. But perhaps a FileName object whose "hash" was computed by hashing the disk file it referred to would avoid magic baked into the cache object? Can objects override how they are hashed, perhaps by overriding how they get pickled? A 'depends' argument isn't really necessary if you're writing your functions yourself because you can always ignore arguments, and it still forces joblib to make an extra copy of the file in the cache.

**Comment by GaelVaroquaux** [comment]
> Can objects override how they are hashed, perhaps by overriding how
> they get pickled?

I would suspect that this should work. It very dangerous though.

For the rest, I think that it is against the philosophy of joblib, which
is to feel simple, minimize user surprise, and try never to break.

**Comment by aarchiba** [comment]
I guess I don't see how "depends" would help here. Would I pass the file contents to "depends" and the file name to the function? That still forces the python code to read in the contents, but I guess that the cache would just store the hash anyway. That seems to deal with the input side. 

The output side is tricky too: for many such functions the "output" is to write specific things to output files rather than returning them. It seems like the solution is to rewrite these functions to act more like python functions passing around the file contents. Perhaps I could write a wrapper object that hung onto filename and contents and was easy to sync with the disk when calling subprocesses.

The point of all this is that I find myself writing makefiles to process data for the same reasons I would use joblib: I want to avoid rerunning tasks unnecessarily. But make is an appalling language, so I'd happily switch to joblib - only most of my inputs and outputs are files on disk, and many of my operations are calling other people's programs that require disk files as input and output.

Maybe I should experiment with a wrapper object, and if I can get it working conveniently, come back and suggest it as an addition to joblib.

**Comment by naught101** [comment]
See https://github.com/yihui/knitr/issues/238

It would probably be simplest if you could pass a second arbitrary function to `Memory.cache` that could hand back a value, and if that value is different to the cached value, then the cache is ignored. Then the user could provide what ever functionality they need. aarchiba could write a simple `hash_dependent_file` function, whereas I would prefer to just check whether any files in a directory have changed,  and so I could just pass a `get_newest_mtime` function.

I would probably restrict it to argumentless functions, for simplicity, and since that would still handle (I think) the vast majority of cases. If the user really needs more functionality than that, they could create it manually..

**Comment by lesteve** [comment]
It feels like you can write this logic outside of joblib so I am going to close this issue. Do shout if you strongly disagree.

Here is a not-standalone snippet to explain a bit what I have in mind (not tested at all):

```py
def user_func(filename):
    cached_func(filename, hash_content(filename))

def func(filename, hash_content_filename):
    # here you just do whatever you were doing without using hash_content_filename

cached_func = memory.cache(func)
```

**Comment by naught101** [comment]
So that hash_content_filename function is never used in func, just is passed to ensure that one arument has changed? That seems like a good work-around, but also seems kind of hacky to be a recommended solution.

If you're caching a lot of functions that's a bit more code to maintain, and code that is (to me at least) not very obvious in its functionality. I'm not across the internals of joblib, so not sure how easy it would be, but if you could have effectively that functionality built in to a separate argument in Memory.cache, that would seem like a cleaner solution to me.

**Comment by lesteve** [comment]
> So that hash_content_filename function is never used in func, just is passed to ensure that one arument has changed?

Yep.

> That seems like a good work-around, but also seems kind of hacky to be a recommended solution.

That's the best I can do I am afraid. Joblib supports caching for functions that given a set of arguments always return the same result. Your original function does not have this property, so you need to write a function that does. I would think that with some work, you could write a generic solution that inspects your function, iterates over the arguments and applies a custom hash key (e.g. based on the argument types or argument names) and also defines the helper function with additional argumetns that is the one that is being cached. My feeling is that this is unlikely to happen inside joblib.
