### ISSUE TITLE
why test_nested_exception_dispatch could get stuck?

### ISSUE THREAD

**Issue by yarikoptic** [joblib/joblib#257]
I thought that it was some system specific but it seems to happen randomly on different systems -- observing it while building fresh debian packages for 0.9.2

**Comment by lesteve** [comment]
I have seen a few stalling builds on Travis every once in a while and I just assumed it was a Travis glitch because I had never seen it when running the tests locally. I could retrieve a couple of instances of those:
https://travis-ci.org/joblib/joblib/jobs/82719092
https://travis-ci.org/joblib/joblib/jobs/85329306

Both of these logs stop with the following output:
```
Make sure that exception raised during dispatch are indeed captured ... 

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

so not sure whether the tests are stuck while running `test_exception_dispatch` or the next test in the list, i.e. `test_nested_exception_dispatch`.

Also both of these Travis failure happens on Python 3, maybe just a coincidence. Are you seeing the same thing @yarikoptic?

I haven't managed to reproduce it locally yet by running 
```
nosetests -s joblib/test/test_parallel.py -m test_nested_exception_dispatch
```

Maybe @ogrisel has suggestions off the top of his head.

**Comment by lesteve** [comment]
> I haven't managed to reproduce it locally yet by running 

I still haven't managed to reproduce locally. @yarikoptic you haven't observed some kind of pattern (python version, platform, etc ...) for this problem by any chance ?

**Comment by yarikoptic** [comment]
as I have mentioned I think it was happening randomly... and thus I think I just rebuilt twice to avoid stuck build.  So to me it felt like a race condition somewhere... I guess we could keep it in the back burner -- if I run into it again, I will try to gain some more insights .  Might be worth testing/running tests in an infinite loop on a slow/busy system to help triggering race condition if that is.  I will try on one such one ;)

**Comment by lesteve** [comment]
This does seem similar to #295 and has been fixed in 0.9.4. @yarikoptic have you seen it happen with 0.9.4 ?

**Comment by yarikoptic** [comment]
I am afraid I have missed 0.9.4 release... I will update the package and report how those builds go. cheers!

**Comment by lesteve** [comment]
Sounds good, let us know !

**Comment by yarikoptic** [comment]
I didn't experience any stalls while building 0.9.4 packages, so I guess it is resolved now. thanks ;-)
