### ISSUE TITLE
Is joblib for Py3 registered right on pypi?

### ISSUE THREAD

**Issue by GaelVaroquaux** [joblib/joblib#272]
Looking at the pypi site, it seems that joblib is not python 3 compatible?
https://pypi.python.org/pypi/joblib#downloads

**Comment by lesteve** [comment]
I just tried and you can pip install with python 3 and it installs the wheel: joblib-0.9.3-py2.py3-none-any.whl.

Are you saying we should not upload the python 2.7 egg i.e. joblib-0.9.3-py2.7.egg to PyPI?

**Comment by GaelVaroquaux** [comment]
Maybe I am wrong. I was just saying that looking at that page, in the column 'Py Version' of the table, I don't see Python 3, and seems thus that Python 3 is not supported.

But maybe it's a bug of the rendering of the table on pypi.

**Comment by lesteve** [comment]
> in the column 'Py Version' of the table, I don't see Python 3, and seems thus that Python 3 is not supported.

I see, I have to admit I never spotted this column before and I am not sure how to do something about it but I can try to have a look.

**Comment by GaelVaroquaux** [comment]
> I see, I have to admit I never spotted this column before and I am not
> sure how to do something about it but I can try to have a look.

If you can't do anything about it, just close the issue.

**Comment by lesteve** [comment]
twine seems to do a nicer job as far as the "Py Version" column is concerned, namely "py2.py3". Maybe a good way to work around the issue is to update the installation instructions to use twine instead? IIRC twine is recommended by PyPA to upload to PyPI anyway (main reason is it doesn't send PyPI credentials in clear)

While I am at it, is there a good reason we need to build an egg if we build a wheel?

**Comment by GaelVaroquaux** [comment]
> While I am at it, is there a good reason we need to build an egg if we
> build a wheel?

Older versions of setuptools?

**Comment by lesteve** [comment]
> Older versions of setuptools?

Fair enough.

**Comment by lesteve** [comment]
> Older versions of setuptools?

Actually couldn't they just use the .tar.gz source distribution?

**Comment by GaelVaroquaux** [comment]
> Actually couldn't they just use the .tar.gz source distribution?

Probably. I don't know what's best. I am lost with Python packaging.

**Comment by lesteve** [comment]
> Probably. I don't know what's best. I am lost with Python packaging.

Not an expert either. I guess I'll just ask @ogrisel when he is back.

**Comment by aabadie** [comment]
Digging this up @lesteve, @GaelVaroquaux.

I read the doc about python packaging here: https://packaging.python.org/en/latest/distributing/#packaging-your-project
As joblib is supporting both python 2 and 3 without compiled code, we probably should try what is mentioned in the "Universal Wheels" section e.g in `setup.cfg`, put
```
[bdist_wheel]
universal=1
```
instead of
```
[wheel]
universal=1
```

and use 
```bash
# setuptools version
python setup.py sdist bdist_wheel upload
```
or
```bash
# twine version (seems to be more secure)
twine upload dist/*
```

**Comment by rth** [comment]
The latest release looks fine https://pypi.org/project/joblib/#files and has universal wheels so this can probably be closed..

**Comment by lesteve** [comment]
Thanks
