### ISSUE TITLE
Nested Parallelism with n_jobs = 1 in outer Parallel does not work in Python 3.5

### ISSUE THREAD

**Issue by arthurmensch** [joblib/joblib#275]
I will yield a minimalistic example ASAP, has anyone experienced this issue before ? Inner Parallel is set with `n_jobs > 1` but runs sequentially if run within a process launched in an outer `Parallel(n_jobs=1)` loop.

It may not be an issue though, but no warning is yielded in this case (in contrast with the case with `n_jobs > 1` in outer loop), which is confusing.

**Comment by lesteve** [comment]
@arthurmensch was it something like this you had in mind:

```py

from joblib import Parallel, delayed

import multiprocessing


def func():
    return multiprocessing.current_process().pid


def parallel_func():
    return Parallel(n_jobs=2)(delayed(func)() for _ in range(2))

if __name__ == '__main__':
    print(Parallel(n_jobs=1)(delayed(parallel_func)() for _ in range(3)))
```

Output:
```
[[4312, 4313], [4317, 4318], [4322, 4323]]
```

It seems to work as expected though, i.e. each call to func is done in a separate process.

Sanity-check you set n_jobs=2 in the outer Parallel call, then you get something like:

```
[[4395, 4395], [4396, 4396], [4396, 4396]]
```

which makes sense since n_jobs is set to 1 (with the warning) in the inner Parallel call.

**Comment by lesteve** [comment]
Closing, since this problem seems to have been fixed since.
