### ISSUE TITLE
Allow passing pathlib.Path to joblib.dump/joblib.load

### ISSUE THREAD

**Issue by anntzer** [joblib/joblib#315]
A minor itch, similar to numpy/numpy#6418: it would be nice if `joblib.dump` and `joblib.load` were able to handle `pathlib.Path` objects as arguments.

**Comment by GaelVaroquaux** [comment]
For dump, I can see a problem looking at the code (an explicit check to a subclass of basestring). This should be fixed by allowing also Path objects in recent Python.

For load, I can't see any problem. If there is one, can you post the traceback here.

For all this, we would very much welcome a pull request fixing these issues and adding a test.

**Comment by anntzer** [comment]
For `load`, `open(filename)` will fail (you need to write `path.open()`, or `open(str(filename))`).  I'll make a PR.
