### ISSUE TITLE
In-memory caching

### ISSUE THREAD

**Issue by anntzer** [joblib/joblib#341]
Sometimes reloading custom objects from the cache can be expensive (but still much faster than recomputing the whole object from scratch), in which case a two-level cache can be useful: results could be first kept in memory, and, after some timeout (LRU/etc.), pushed to the hard drive for longer-time persistence.
Is this something that joblib's architecture may easily allow?

**Comment by aabadie** [comment]
> Is this something that joblib's architecture may easily allow?

@anntzer, I just created #351 which allows this (still WIP).

**Comment by lesteve** [comment]
> @anntzer, I just created #351 which allows this (still WIP).

I don't think this is quite @anntzer had in mind since #351 is only changing dump/load and not the cache. This could potentially make it a bit easier to implement this feature though since we can dump into BytesIO object.

My opinion on this issue is that we would need a strong use case where loading from disk really is the bottleneck. As far as I know we haven't encountered cases like this in our usage of joblib.

**Comment by anntzer** [comment]
I was actually thinking of a layer where the objects are not serialized at all, just kept in memory as full objects (as an old-style memoization cache).  But I agree that would be a pretty specific requirement.

**Comment by lesteve** [comment]
Closing as I don't think this one will be on the roadmap any time soon.
