### ISSUE TITLE
Terminating a Parallel process early

### ISSUE THREAD

**Issue by MartinHjelm** [joblib/joblib#356]
Seems like there is no mention in the documentation for terminating a parallel process prematurely. I figured I would have better luck asking or submitting a feature request here than on Stack Overflow. For example if I run a process that computes a score 

    scores = Parallel(n_jobs=3,verbose=0)(delayed(computeScore)(X,y,idx,**kwargs) for idx in indices)

Now if any of the scoring functions reports a score above a certain threshold I would want to terminate the Parallel process early and not run all the loops till it finishes.

**Comment by lesteve** [comment]
You could raise an exception in your `computeScore` function and have a try/catch around your Parallel call.

```python

def compute_score():
    ...
    if score > threshold:
        raise ValueError("Got score {} which is too high".format(score))

def main():
    try:
        Parallel(...)(delated(compute_score)(...))
    except ValueError:
        pass
```

You may want to use a custom exception rather than a ValueError. Note: you won't be able to access any of the results from the other processes that already completed but from your description it seems fine, i.e. you want to throw away all the results of the Parallel call.

**Comment by MartinHjelm** [comment]
@lesteve thanks! I do need the results but I could easily pickle it and then load it.

**Comment by lesteve** [comment]
> I do need the results

In that case it looks like the PR #367 might interest you.
