### ISSUE TITLE
load fails when dump use pickle.HIGHEST_PROTOCOL in Python 3

### ISSUE THREAD

**Issue by zhuoqiang** [joblib/joblib#362]
in master branch a96878e (version 0.10.0.dev0), the following code gives `KeyError`

```py
import pickle
import numpy as np
import joblib

a = np.zeros((1, 235), np.uint32)
joblib.dump(a, 'tmp.jl', protocol=pickle.HIGHEST_PROTOCOL)
joblib.load('tmp.jl')
```

That is: joblib seems do not support load data which saved with `pickle.HIGHEST_PROTOCOL`

**Comment by lesteve** [comment]
I can reproduce this (only happens on Python 3 on master, i.e. not 0.9.4), not sure why this happens. In the meantime, you can leave the protocol argument unset in joblib.dump. My guess is you are not likely to see big changes in performance but let us know if you do.

**Comment by lesteve** [comment]
@zhuoqiang if you could do a git bisect to see where the regression was introduced it would be very helpful.

**Comment by lesteve** [comment]
@aabadie doing a git bisect it was introduced by the single-file persistence: 8ed578b69064f0867d3b019a5fc0a908847e3b15.

Do you mind taking a look?

**Comment by aabadie** [comment]
> Do you mind taking a look?

Sure !

**Comment by aabadie** [comment]
@lesteve, digging into it, the single file persistence is indeed broken with pickle protocol 4. The binary streams generated are really different and explain what is problem:
* if pickle protocol is <= 3, the array wrapper is first written in the binary stream, then the content of the array is written => loading works
* with pickle protocol > 3 (e.g 4, le most recent, from python 3.4), the array wrapper is written after the content of the array in resulting byte stream. That's why the reloading doesn't work.

The fix might not be so easy to implement, I have to think of it.

**Comment by lesteve** [comment]
Indeed this seems to be the case that the data is not written in the same order. Do you have an intuition why?

**Comment by aabadie** [comment]
> Do you have an intuition why?

I guess the pickle has changed a little but I still have to understand what is the difference.
