### ISSUE TITLE
joblib.delayed does not work as decorator

### ISSUE THREAD

**Issue by graipher** [joblib/joblib#386]
These two usages of `delayed` work:

``` python
from joblib import delayed

def f(n):
    return n**2

delayed(f)(2)
# (<function f at 0x7f939eb3fe60>, (2,), {})

h = delayed(f)
h(2)
# (<function f at 0x7f939eb3fe60>, (2,), {})
```

The latter usage makes me think this could be used like any other decorator. This is supported by the documentation:

> ```
> joblib.delayed(function, check_pickle=True)
> 
> Decorator used to capture the arguments of a function.
> ```

However, this fails:

``` python
from joblib import delayed

@delayed
def g(n):
    return n**2

# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 158, in delayed
#    pickle.dumps(function)
#  File "/usr/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
#    raise TypeError, "can't pickle %s objects" % base.__name__
#TypeError: can't pickle function objects
```

It does, however, work with setting `check_pickle` to `False`:

``` python
def delayed_no_pickle(func):
    return delayed(func, False)


@delayed_no_pickle
def f(n):
    return n**2
```

I tried this with Python 2.7.12

**Comment by GaelVaroquaux** [comment]
By doing this, you're breaking pickling, which is a bad idea.

Arguably, this is because the decorate function is not well written, and could be written to not break pickling, as explained here:
http://gael-varoquaux.info/programming/decoration-in-python-done-right-decorating-and-pickling.html

If you want to submit a PR implementing this pattern, I think that we could consider it for merging (subject to debate, see below).

That said, I think that using decorators for this purpose isn't a great idea: the behavior of the function is so massively changed that it seems important to me to keep around the original function.

**Comment by lesteve** [comment]
> That said, I think that using decorators for this purpose isn't a great idea: the behavior of the function is so massively changed that it seems important to me to keep around the original function.

Agreed. Also you generally want to have the original function around, for example if you want to further debug an exception that happened in the Parallel call. I don't really see any advantage of using a decorator here I have to say.
