### ISSUE TITLE
Writable output numpy arrays hashed to the same memmap

### ISSUE THREAD

**Issue by maciejkula** [joblib/joblib#436]
I'm using `Parallel` to run jobs that all write to (large) output numpy arrays. I allocate these in advance (as zeros), then pass into the functions that are executing in parallel to be populated.

In my case, these are distinct arrays of zeros of the same shape and dtype; for that reason they are all hashed to the same value by the Joblib hashers (https://github.com/joblib/joblib/blob/e82b5d6684fcb61b0f778df3e29d2985a1c54208/joblib/hashing.py#L52), and so end up sharing the memory map objects Joblib creates. As a consequence my jobs, instead of producing distinct outputs, end up writing over each other.

This behaviour is perfectly fine when the memmap mode is read-only, but is wrong when the memmap mode allows writing.

One solution is to include the object identity in the hash whenever the memmap mode allows writing.

**Comment by lesteve** [comment]
@maciejkula I put together a snippet according to your description, can you confirm this is a good model of what you are doing?

```py
import numpy as np

from joblib import Parallel, delayed


def func(arr, value):
    arr[:] = value
    return arr


arrays = [np.zeros((10, 10), dtype='float64') for i in range(10)]

results = Parallel(mmap_mode='w+', max_nbytes=0, n_jobs=2)(
                       delayed(func)(arr, i) for i, arr in enumerate(arrays))

print([r.max() for r in results])
```

Output:
```
[memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0), memmap(9.0)]
```

**Comment by maciejkula** [comment]
Apologies for not getting back to you sooner!

Yes, that's exactly the symptom. I realize this is somewhat off the beaten path, but is a pain to diagnose.

**Comment by lesteve** [comment]
> Yes, that's exactly the symptom. I realize this is somewhat off the beaten path, but is a pain to diagnose.

I can imagine that. I'll try to get back to this beginning of next week.

**Comment by maciejkula** [comment]
I'm pretty sure it's because arrays of the same type and shape and with the same values hash to the same value and so are treated as identical.

If you replaces `np.zeros` with `np.random.random` in you script above, you get the expected result:
```python
import numpy as np

from joblib import Parallel, delayed


def func(arr, value):
    arr[:] = value
    return arr


arrays = [np.random.random((10, 10)) for i in range(10)]

results = Parallel(mmap_mode='w+', max_nbytes=0, n_jobs=2)(
                       delayed(func)(arr, i) for i, arr in enumerate(arrays))

print([r.max() for r in results])
```
Output:
```
[memmap(0.0), memmap(1.0), memmap(2.0), memmap(3.0), memmap(4.0), memmap(5.0), memmap(6.0), memmap(7.0), memmap(8.0), memmap(9.0)]
```

I'm happy to work on a PR if you think this is worth solving.

**Comment by lesteve** [comment]
Agreed. This is a bug that we should try to fix.

I had a chat with @ogrisel and he thinks that for your use case, you should either:
* create the array in the worker process (i.e. in `func` in the snippet below)
* create mmap yourself before passing them to Parallel. There is an example doing that [here](https://pythonhosted.org/joblib/parallel.html#manual-management-of-memmaped-input-data)

**Comment by elsander** [comment]
This issue has been up for a while, but I can still reproduce it. I've been looking into it, and like @maciejkula suggests, a fix could be as simple as adding `id(obj)` to the tuple of items to hash.

However, this will necessarily change the expected behavior in some cases. For example this test should no longer pass (which makes sense, because it's essentially testing the existence of the buggy behavior): https://github.com/joblib/joblib/blob/8892839cb883b95fd2de3656bf719488eacb851f/joblib/test/test_hashing.py#L124

I can submit a PR with my fix today or this weekend.

**Comment by ogrisel** [comment]
Indeed. Inthe past we had `id(obj)` as part of the filename instead of the content hash but this could cause collisions in case of quick GC in the parallel iterator (Python tend to recycle object identifiers very quickly, I assume they are derived from the memory address of the object). But combining the hash of the content + `id(obj)` should indeed fix the issue while not introducing any new collision.
