### ISSUE TITLE
backend.abort_everything hangs when called programmatically

### ISSUE THREAD

**Issue by sknat** [joblib/joblib#508]
I'm trying to abort a joblib computation programmatically (when used in a GridSearchCV - like context)

* Doing `parallel._backend.abort_everything(ensure_ready=False)` seems to hang
* Also tried several combinations of dropping `parallel._jobs`, releasing locks but nothing seems to be working...
* Only `self.parallel._aborting = True` does the work, but it waits for all ongoing jobs to join (which can be extremely slow)

Am I missing a way to do this ?

**Comment by ogrisel** [comment]
I am not sure whether this behavior reflects a bug or not but `parallel._backend.abort_everything(ensure_ready=False)` is definitely note part of the public API.

We don't have any public API to cancel ongoing work.

**Comment by sknat** [comment]
Thanks for the reply,
Effectively it's not an issue, I was more asking for advice on how to do this / if it was feasible (even if there is no intent for this feature to be part for the public API)

**Comment by lesteve** [comment]
@sknat please close the issue if you feel your question has been answered. This help maintaining sanity in our issue tracker.

**Comment by sknat** [comment]
@lesteve ok :)
my question was partially answered though : I understand there is no public API to do that, but is there a *not too complicated* way to do that ?

**Comment by lesteve** [comment]
AFAIK there is no supported way to do this. You may find work-arounds to do what you want but there is no guarantee that it will keep working in the future.

Out of curiosity can you explain your use case in more details, i.e. why do you want to abort a grid search in the middle of it?

**Comment by sknat** [comment]
Ok, that's also what I understood from the source code... Just didn't want to be missing something obvious.

For the use case of aborting the gridSearch, it's in the case of a randomized grid. I wanted to be able to interrupt the computation after some amount of time, and still keep the best set of parameters tested so far.

**Comment by ogrisel** [comment]
I am not sure if it's feasible without auditing the code of both multiprocessing and joblib (for the default multiprocessing backend).

For the threading backend it should be even more problematic as interrupting threads is not possible in general.

Can you tell us a bit more about your usecase? Are you doing interactive computing? 

If you want to use a user facing async API why don't you use the `concurrent.futures.*Executor` API instead of the joblib synchronous API?

**Comment by ogrisel** [comment]
I had not seen your last comment. What you can do is use the `RandomizedSearchCV` instead of `GridSearchCV` and fix the amount of iterations (e.g. n_iter=10) and call it several consecutive times (with different values for `random_state`). Each time store the results to avoid loosing them.

Using `GridSearchCV` will run the exploration in a deterministic order that is provably more biased and therefore less efficient to find a good solution if you have a finite compute budget / patience.
