### ISSUE TITLE
failed with wrapped function on win10

### ISSUE THREAD

**Issue by a1a2y3** [joblib/joblib#545]
Parallel(n_jobs=1)(delayed(sqrt)(i ** 2) for i in range(100))           ------0.004s
Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(100))           ------0.516s

def fun0(i):
    from math import sqrt
    return sqrt(i)
Parallel(n_jobs=2)(delayed(fun0)(i ** 2) for i in range(100))          -------nearly 200s

I can't find the reason.
My enviroment is windows10+anaconda+python3.6+vs2015.

**Comment by a1a2y3** [comment]
Solution from http://pythonhosted.org/joblib/parallel.html#common-usage


Under Windows, it is important to protect the main loop of code to avoid recursive spawning of subprocesses when using joblib.Parallel. In other words, you should be writing code like this:

import ....

def function1(...):
    ...

def function2(...):
    ...

...
if __name__ == '__main__':
    # do stuff with imports and functions defined about
    ...

No code should run outside of the “if __name__ == ‘__main__’” blocks, only imports and definitions.

**Comment by lesteve** [comment]
Thanks for finding the solution to your problem and posting it.

Welcome to github here are a few pointers to help you get started:
* github use markdown which is why the formatting in your messages is a bit off. Read about markdown [here](https://guides.github.com/features/mastering-markdown/)
* Readability counts, a lot! Please use triple back-quotes aka [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to format error messages code snippets. Bonus points if you use [syntax highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) with `py` for python snippets and `pytb` for tracebacks.
* you can close the issue when the issue has been solved. I'll do it for you this time but please remember for next time!
