### ISSUE TITLE
Checking if a cached result exists?

### ISSUE THREAD

**Issue by mfranzs** [joblib/joblib#668]
I'm using `Memory` to cache a function. Is there a way to check if a saved result already exists from a previous evaluation of the function?

**Comment by GaelVaroquaux** [comment]
> Is there a way to check if a saved result already exists from a previous evaluation of the function?

No simple way, unfortunately. The decorated function has a bunch of
private methods that can easily be used to test the presence in cache, in
particular: _get_output_idendifiers to know where it is stored.

**Comment by lesteve** [comment]
Related to https://github.com/joblib/joblib/pull/407. I worked on something similar a while ago, see [this](https://github.com/joblib/joblib/compare/master...lesteve:requires-computation?expand=1). My main motivation at the time was that the `_requires_computation` method could be overriden by people who want cache with an expiry date.

Note that my branch has conflicts with master that will need to be solved. It is not completely trivial because of the introduction of store backends.

**Comment by nwilming** [comment]
@lesteve I created a PR (#730) that pretty much does what your PR did but uses the new backend implementation. Maybe this can solve this problem.
