### ISSUE TITLE
Stale file handle IOError in Memory.reduce_size on Python 2

### ISSUE THREAD

**Issue by josiahjohnston** [joblib/joblib#672]
Great project! I really like the functionality and stability you all have built, and it's taken me several months to find my first issue with your library.

I'm running joblib.memory in parallel, writing to an NFS drive. I encountered an error that yields the message "ERROR - [Errno 116] Stale file handle". As best I can tell, this occurs during calls to `memory.reduce_size()` because two processes were trying to delete a directory at the same time, and the directory disappeared from the NFS mount before the second process was finished.

It looks like the StoreBackendMixin and FileSystemStoreBackend classes of joblib._store_backends attempt to address these race conditions by catching and ignoring OSError's. I even found a mention of Stale File Handles & errno 116 in a comment in StoreBackendMixin.reduce_store_size(). However, on my system, a stale file handle results in a IOError rather than an OSError (Ubuntu 16.04, Python 2.7.12, joblib 0.11, doing I/O from an NFS on Amazon EC2 cloud). 

Would it be reasonable to also catch & pass on IOError's in each place of joblib._store_backends where you are currently catching OSError's? If you wanted to be more specific, you could do something like:

```
import errno
...
except IOError as e:
    if e.errno == errno.ESTALE:
        pass
    else:
        raise e
```

In the meanwhile, I'll do a workaround by wrapping my calls to `reduce_size()` in a try statement and use that except/pass to ignore stale file handles.

**Comment by lesteve** [comment]
Thanks for the kind words and the clear bug report! It looks like an oversight and I am guessing this kind of edge cases were only tested with Python 3.

A PR would be more than welcome. I would be fine with just replacing `except OSError` by `except (OSError, IOError)` in this code:
https://github.com/joblib/joblib/blob/902fb6bbcf75c461d1b6703e5a01605fc592f214/joblib/_store_backends.py#L285-L292

together with adding a comment that on Python 2 you get IOError rather than OSError.

If you have any more feedback on `reduce_size`, don't hesitate! I would guess it is a part of `Memory` that is not used by most people.
