### ISSUE TITLE
joblib for shared list 

### ISSUE THREAD

**Issue by houssem1992** [joblib/joblib#717]
I Want to use joblib to parallelize a sliding windows task to search objects in images. the Problem is that the for loop of my code have a shared list (using append) which will be changed every time when the prediction of my classifier is true. (see the code below) It is possible to do this task with joblib?

`    bboxes = []
    for xb in range(nxsteps+1):
        for yb in range(nysteps+1):
            ypos = yb*cells_per_step
            # some code there
            test_prediction = svc.predict(test_features)

            if test_prediction == 1:
                xbox_left = np.int(xleft)
                ytop_draw = np.int(ytop)
                win_draw = np.int(window)
                box = [(xbox_left+xstart, ytop_draw+ystart), (xbox_left+win_draw+xstart,ytop_draw+win_draw+ystart)]
                bboxes.append(box)`

**Comment by lesteve** [comment]
> Problem is that the for loop of my code have a shared list (using append)

It would recommend you modify your code to avoid passing a list to your function and modifying it inside your function (if that is what you are doing, it's hard to tell from your snippet). For example instead of appending the result to your list in your function, return the result.

I am going to close this issue because this feels like a generic programming question than something related to joblib.
