### ISSUE TITLE
Forward URL from pythonhosted to readthedocs

### ISSUE THREAD

**Issue by GaelVaroquaux** [joblib/joblib#737]
#724 is still not really fixed: Now that we have moved the docs from pythonhosted to readthedocs, we need a forward from the former to the latter: Google and old links will still land on the former.

**Comment by GaelVaroquaux** [comment]
Reopening as not fixed by #738 though: we would need redirects from pythonhosted (via a pure html redirect, unless we can set up an http one, which would be better)

**Comment by lesteve** [comment]
I deleted the doc on PyPI on https://pypi.org/manage/project/joblib/documentation/ following the instructions in https://github.com/pypa/pypi-legacy/issues/700#issuecomment-378470711.

Now that https://pythonhosted.org/joblib/ is broken Google should catch up and not show a broken link.

Let's close this one and reopen if this is not fixed in a say a week.

**Comment by lesteve** [comment]
I just double-checked https://www.google.com/search?hl=en&q=joblib. It looks like pythonhosted is slowly going down in the rankings, now it is the fourth hit after github, PyPI and readthedocs:

![image](https://user-images.githubusercontent.com/1680079/44589537-181ad480-a7b9-11e8-9b8d-7f95cca183bf.png)
