### ISSUE TITLE
Parallel uses all cpus even when n_jobs is set to use fewer

### ISSUE THREAD

**Issue by hermidalc** [joblib/joblib#793]
When I use joblib.Parallel within scikit-learn 0.19.2, either directly or via e.g. GridSearchCV, the n_jobs parameter doesn't control the total number of cpus that can be used in parallel, only the number of distinct parallel worker processes and each process will utilize multiple cpus such that all cpus are always utilized no matter what n_jobs is set to.

For example, on a 4 core/8 logical cpu setup, if I set n_jobs=2 then Parallel will run two worker processes (which I see in top) but each will utilize approx 400% cpu (so each uses 4 logical cpus).  I cannot get it to just use two logical cpus.  Is this behavior normal and I misunderstanding usage, or is this a bug?

Fedora Linux 4.18.14-200.fc28.x86_64 
Anaconda 5.2.0
Python 3.6.5
scikit-learn 0.19.2 (which I believe uses joblib 0.11)

**Comment by tomMoral** [comment]
This is due to third party libraries (in your case probably `numpy` with `openblas` or `mkl`) which parallelize underlying operations in each process.

You can disable this behavior with `joblib0.11` by setting the environment variables `MKL_NUM_THREADS=1 OMP_NUM_THREADS=1`. Note that this might slow down computation that are not run in parallel as this means that all algebric operations will be single threaded. This is the default behavior in the joblib workers starting from `joblib0.12`.

For more information, see [this part of the `joblib` documentation](https://joblib.readthedocs.io/en/latest/parallel.html#avoiding-over-subscription-of-cpu-ressources)

**Comment by hermidalc** [comment]
Thanks @tomMoral, I just preceded my script calls with those env vars and indeed that does change the CPU usage to what one would expect for their n_jobs setting.  I'm glad I asked about this, as you wrote in the joblib doc reference above, I see that my previous model selection runs were significantly slower by not setting these env vars to single threaded as CPUs got way oversubscribed and there was significant system CPU usage overhead just to handle everything.
