### ISSUE TITLE
Silent failure if Path("...") is passed - BUG

### ISSUE THREAD

**Issue by N-McA** [joblib/joblib#816]
The following code shows a silent failure when a Path is passed.

```
from pathlib import Path
from joblib import Memory

m1 = Memory(Path('../joblib-cache'), verbose=True)
m2 = Memory('../joblib-cache', verbose=True)

@m1.cache
def foo1(x):
    return x

@m2.cache
def foo2(x):
    return x

foo1(3)
foo2(3)
```

Printing only the verbose joblib output for foo2, and not caching foo1.

`python --version == 3.7 ; joblib.__version__ == 0.13.0`

May have time to produce a pull request tomorrow.

**Comment by tomMoral** [comment]
Yes it looks like it is due to [`_store_backend_factory`](https://github.com/joblib/joblib/blob/master/joblib/memory.py#L99) which only accepts `_basestring` or `StoreBackendBase` objects.

It could easily be updated to accept `Path` object. Also, raising a warning when `None` is return and `location` is not `None` would improve readability.
