### ISSUE TITLE
No handlers could be found for logger "concurrent.futures"

### ISSUE THREAD

**Issue by zihaozhu93** [joblib/joblib#819]
i wrote a class, and using joblib.Parallel to call its method, like:

class A():
  def fun1(xx):
    ...
  def fun2(xx):
    ...

a = A()
Parallel(n_jobs=-1)(delayed(a.fun1)(a.fun2(xx)))

and run several iterations, then terminated with errors:

No handlers could be found for logger "concurrent.futures",
anyone has any ideas?
thx

**Comment by psurya55554** [comment]
did u get that?
if so please tell how

**Comment by ssb22** [comment]
Don't know about OP but I get this error on Python 2.7 if I use `concurrent.futures` and try to call `.result()` of a submitted job from inside an `.add_done_callback` method, in the case where the job has raised an exception.  For example:

    import concurrent.futures
    def bad_function(): assert 0
    def callback(f): f.result()
    executor = concurrent.futures.ProcessPoolExecutor()
    job = executor.submit(bad_function)
    job.add_done_callback(callback)

I believe this is happening because `callback` runs in a new thread of the parent process, and exception handling in threads does not appear to be set up very well.  The problem goes away if I just call `job.result()` in the main thread, instead of using `add_done_callback`.  But in my application I wanted a progress indicator of how many of the hundreds of jobs I'd submitted had completed, and of course I didn't know which order to call their (blocking) `.result()` methods (calling them in the same order as I submitted the jobs did not help), so I used a `Queue` to avoid calling `.result()` from inside the callback:

    import concurrent.futures
    try: import Queue as queue # Python 2
    except: import queue # Python 3
    queue = queue.Queue()
    def bad_function(): assert 0
    def callback(f): queue.put(f)
    executor = concurrent.futures.ProcessPoolExecutor()
    job = executor.submit(bad_function)
    job.add_done_callback(callback)
    queue.get().result()
