### ISSUE TITLE
not possible to use joblib as background thread

### ISSUE THREAD

**Issue by Krzysiaczek99** [joblib/joblib#865]
when I try to start parallel loop as background thread I'm getting 

/usr/anaconda3/lib/python3.7/site-packages/joblib/parallel.py:673: UserWarning: Loky-backed parallel loops cannot be nested below threads, setting n_jobs=1
  **self._backend_args)
[Parallel(n_jobs=8)]: Using backend SequentialBackend with 1 concurrent workers.

Attempt to rename thread to 'MainThread' don't help

**Comment by wangyexiang** [comment]
> /usr/anaconda3/lib/python3.7/site-packages/joblib/parallel.py:673: UserWarning: Loky-backed parallel loops cannot be nested below threads, setting n_jobs=1
> **self._backend_args)
> [Parallel(n_jobs=8)]: Using backend SequentialBackend with 1 concurrent workers.
> 
> Attempt to rename thread to 'MainThread' don't help

Same issue. when I try to use gridsearch(sklearn api) in a QThread(multithread of PyQt), and set n_jobs = -1, I get the same warning. Parallel searching doesn't work.

How to fix it?  @tomMoral@ogrisel

**Comment by tomMoral** [comment]
Hello,

Thanks for raising this issue. Indeed, I think with the current API, it is not possible to run `joblib` in a background thread. The issue is in [_parallel_backends](https://github.com/joblib/joblib/blob/master/joblib/_parallel_backends.py#L496), where we make sure the Parallel loop is called from a `_MainThread`.

We would need to add an option to allow explicitly running `Parallel` in a background thread. I did a tentative implementation in PR #919 , not sure it is really the right solution. If you have the time to try it, please report back on the PR.
