### ISSUE TITLE
JOBLIB_MULTIPROCESSING does not exist in documentation

### ISSUE THREAD

**Issue by Arfey** [joblib/joblib#929]
I spent a lot of time to try understand why `celery` generate zombie processes. As result I find that `joblib` initialize semaphore and after set `JOBLIB_MULTIPROCESSING` to `0` all work correct.

I think that add some description about `JOBLIB_MULTIPROCESSING `  to documentation is good idea.

**Comment by tomMoral** [comment]
#893 has fixed the mechanism that caused the spawning of the semaphore tracker on `joblib` import. It has not been released yet.

Setting `JOBLIB_MULTIPROCESSING` to 0 completely deactivate the parallelism in `joblib` and is mainly used for testing purposes. I am not sure it is necessary to document it as it kind of defeats the purpose of `joblib`.

**Comment by Arfey** [comment]
Agree with you. I close this issues but please make a release.

**Comment by joncourt** [comment]
we've got models from our data scientists that use sklearn - and consequently joblib. We're finding perf improvements of about 20 - 30% by disabling joblib multiprocessing. When profiling it it's spending a lot of time in unnecessary waits it seems.

When using kubernetes to handle spawning many instances a multithreaded instance doesn't seem to make sense to me - the parallelism is instance by instance rather than thread by thread (event-loops are still relevent of course).

I think documenting this feature is useful where a model has been packaged up for execution in a kubernetes base application where you'll expand the number of pods rather than threads.

I don't yet know enough about sklearn to know whether running models that use it in a kubernetes environment even makes sense. I expect to work through that over the next few days or weeks.
