### ISSUE TITLE
Wrong number of workers reported by effective_n_jobs

### ISSUE THREAD

**Issue by glemaitre** [joblib/joblib#984]
I want to highlight something which looks weird to me (not sure yet if this is a bug). I made a snippet which is a pattern that we use in scikit-learn.

```python
from joblib import Parallel, delayed, effective_n_jobs, parallel_backend
from joblib.parallel import get_active_backend


def func(x):
    return x ** 2


class Klass:
    def __init__(self, n_jobs=None):
        self.n_jobs = n_jobs

    def func(self, x):
        n_jobs = effective_n_jobs(self.n_jobs)
        print(
            f"Number of effective jobs found: {effective_n_jobs(self.n_jobs)}"
        )
        backend, backend_n_jobs = get_active_backend()
        print(
            f"Current backend used: {backend}"
        )
        print(
            f"Number of jobs in the backend: {backend_n_jobs}"
        )
        return Parallel(n_jobs=n_jobs)(delayed(func)(i) for i in x)


n_jobs = 4
with parallel_backend("threading", n_jobs=n_jobs):
    r = Klass().func(range(10))
```

```
Number of effective jobs found: 1
Current backend used: <joblib._parallel_backends.ThreadingBackend object at 0x7f946468d810>
Number of jobs in the backend: 4
```

If I am not wrong, one would expect to make the `Parallel` call with `n_jobs=4`. However, `effective_n_jobs` will report `n_jobs=1` due to:

https://github.com/joblib/joblib/blob/1753c3bcb1d8430439ce48a1ef4e866166f34296/joblib/_parallel_backends.py#L232-L235

I would have expected `parallel_backend` to overwrite the number of jobs if not specified in the estimator but I am not sure about it.

NB: found during investigating https://github.com/scikit-learn/scikit-learn/issues/15978

**Comment by glemaitre** [comment]
I don't know if this is a fix but one could expect:

```python
def effective_n_jobs(n_jobs=-1):
    backend, backend_n_jobs = get_active_backend()
    if n_jobs is None:
        return backend_n_jobs
    return backend.effective_n_jobs(n_jobs=n_jobs)
```

**Comment by tomMoral** [comment]
This is weird indeed.
There is a discrepancy between the result of `effective_n_jobs(None)` and the number of workers used for `Parallel(n_jobs=None)` due to the different behavior in [Parallel](https://github.com/joblib/joblib/blob/master/joblib/parallel.py#L623) and in  [effective_n_jobs](https://github.com/joblib/joblib/blob/master/joblib/parallel.py#L366).

There is 2 solutions:
- Either we change `effective_n_jobs` as Guillaume mentioned.
- Or we store the `backend_n_jobs` in the backend and we let `backend.effective_n_jobs` do the work. However, If I recall correctly, I think we did not go with this solution as it was hard to cope with the way we defined nested backends and with the backward compatibility. But it would be probably better in the long run?

not sure what other are thinking here? @ogrisel @GaelVaroquaux

**Comment by ogrisel** [comment]
Yes I don't recall exactly. This is probably just a bug. Let's try to implement @glemaitre in a PR. Shall I do it?

**Comment by glemaitre** [comment]
> Let's try to implement @glemaitre in a PR

Not me but the solution :)

> Shall I do it?

I can do it with a unit test.

**Comment by ogrisel** [comment]
Thanks!

**Comment by GaelVaroquaux** [comment]
> >     Let's try to implement @glemaitre in a PR

> Not me but the solution :)

I would so much like to have @glemaitre in joblib. It would be a major
feature!
